### ISSUE TITLE
2 Erros, verb in the past tense

### ISSUE THREAD

**Issue by avr00** [vilicvane/a-plus-dictionary#2]
Your application is really really helpful it helps me a lot considering that I'm learning but it has just 2 errors...

1) When you try to translate or show a english word that is in the past tense, such as, learnt, bought, sang, watched, it appears as a normal verb

here you have a picture to a better explanation: http://img571.imageshack.us/img571/1995/b4i4.png

2) The second Bug is when you try search a verb in the past tense it doesn't appear, example: http://i.imgur.com/GxcRNeS.png

and thank you again for this great application! if you fix these issues this application will be the best dictionary

**Comment by vilicvane** [comment]
hi Blake, thanks for your feedback.

but actually it's not a bug. instead I made it so on purpose. though I know this solution is far from perfect.

I will try to provide more detailed information in the result later if I get time, but recently I am busy with something else.

thanks anyway.

Sent from my Windows Phone

**Comment by vilicvane** [comment]
hi Blake again, I have made some changes to this dictionary recently, now it's still showing the normal words, but in the popup, the list of its tenses is now available. hope it could somewhat fit your needs. :)

**Comment by avr00** [comment]
it still doesn't show the past tense verbs look at the picture http://i.imgur.com/rAcB2Pa.png

Date: Sun, 15 Dec 2013 23:25:28 -0800

**Comment by vilicvane** [comment]
yeah, i understand this. you can check the popup by clicking the icon or use shortcut Ctrl+Shift+A, and see the tenses of current word.but i think most of the time the user would want to know the original words, so...

VILIC VANEDuring the transition from a computer geek to a physics nerd...Website - Facebook - Twitter

Date: Thu, 19 Dec 2013 07:24:36 -0800

**Comment by avr00** [comment]
I would not say so, i think people want to translate what they have click and know the pronunciation, i think it is impossible to fix so far because your application is pretty similar to the google's one and the google's one doesn't show the past tense verbs as well... believe me it would be really good if your app worked like when you click on one word you get the translation and definition of THIS word.
Date: Thu, 19 Dec 2013 09:29:25 -0800
